program TIDES (INPUT, OUTPUT);

const
   MINSPERHR        = 60;
   MINSPERDAY       = 1440;
   MINSPERTIDECYCLE =  745;

var
   TODAYSDATE, TIDEHR,
   EVENTDATE, EVENTHR,
   MINSTOHIGHTIDE, MINSTOEVENT, ELAPSEDTIME: INTEGER;
   TIDECYCLES:REAL;

begin
   REA
end.


